service: migrate

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:eu-west-1:006483271430:rackspace-migration-production
        - arn:aws:sqs:eu-west-1:006483271430:rackspace-migration-production-DLQ
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::rackspace-image-archive
        - arn:aws:s3:::rackspace-image-archive/*
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 55

package:
  exclude:
    - contrib/**
    - build/**
    - .eggs/**
    - .cache/**
    - serverless_python_ping.egg-info/**
    - node_modules/**
    - .serverless/**
    - deploy/**
    - tests/**

plugins:
  - serverless-python-requirements
  - serverless-plugin-lambda-dead-letter
custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy:
      - pytest
      - boto3
      - botocore
      - docutils
      - jmespath
      - python-dateutil
      - s3transfer
      - six

functions:
  write_point:
    handler: migrate.interfaces.aws_lambda.consume_queue
    deadLetter:
      targetArn: arn:aws:sqs:eu-west-1:006483271430:rackspace-migration-production-DLQ
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-1:006483271430:rackspace-migration-production
          batchSize: 10
